### ISSUE TITLE
latest release tag is '1.0.3.157'. binary is '1.0.3.147'

### ISSUE THREAD

**Issue by maelcum** [XhmikosR/perfmonbar#10]
probably just a typo in the release tags.

**Comment by maelcum** [comment]
update: this also explains the broken link on the homepage (https://xhmikosr.github.io/perfmonbar) where "Download Installer" points to 'https://github.com/XhmikosR/perfmonbar/releases/download/1.0.3.147/PerfmonBar.1.0.3.147.exe' (since there is no folder 1.0.3.147, just 1.0.3.157.

**Comment by XhmikosR** [comment]
Damn, thanks for the issue.

I will nuke the 1.0.3.157 release for now.

**Comment by XhmikosR** [comment]
Fixed.

**Comment by maelcum** [comment]
Lightspeed reaction time... Awesome!! thumbsup
