### ISSUE TITLE
OffsetX?

### ISSUE THREAD

**Issue by andrizmitnick** [XhmikosR/perfmonbar#11]
it looks out of place, how i can configure for the horizontal alignment?

**Comment by XhmikosR** [comment]
https://github.com/XhmikosR/perfmonbar/blob/master/src/config.xml#L16

**Comment by andrizmitnick** [comment]
![notepad_EhiVkvxY1p](https://user-images.githubusercontent.com/21377475/77294596-24f60600-6d17-11ea-90ad-833c3be4e49c.png)


I'm not sure why it doesn't work ._.
thanks before btw

**Comment by XhmikosR** [comment]
You need to set the offset once per page. Also you need to reload the config with right clicking on Perfmonbar after you make any changes.
