### ISSUE TITLE
Can perfmonbar take maximum of all column output of type perf

### ISSUE THREAD

**Issue by andibuwono** [XhmikosR/perfmonbar#12]
Hi thank for awesome utility program.

I'm trying to get my computer CUDA load/utilization, but the problem is CUDA id is dynamic, as shown below.

It keeps add new PID as new task is added. Is there any method to calculate the maksimum load of these out type perf column output. (the PID can grown from and reduce to 1 according to the work load)

Thanks

> 'PS C:\Users\andib> typeperf "\GPU Engine(*_Cuda)\Utilization Percentage"

> '"(PDH-CSV 4.0)","\\ANDINI\GPU Engine(pid_4_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage"
> '"05/16/2020 08:41:18.335","0.000000"
> '"05/16/2020 08:41:19.336","0.000000"
> '"05/16/2020 08:41:20.337","0.000000"

> 'PS C:\Users\andib> typeperf '\GPU Engine(*_Cuda)\Utilization Percentage'

> '"(PDH-CSV 4.0)","\\ANDINI\GPU Engine(pid_2616_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_16720_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_3272_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_16660_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_4_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage"
"05/16/2020 08:49:10.558","0.000000","0.000000","0.000000","0.000000","0.000000"
"05/16/2020 08:49:11.559","0.000000","0.000000","0.000000","0.000000","0.000000"
"05/16/2020 08:49:12.562","0.000000","0.000000","0.000000","0.000000","0.000000"
"05/16/2020 08:49:13.566","0.000000","0.000000","0.000000","0.000000","0.000000"
"05/16/2020 08:49:14.568","0.000000","0.000000","0.000000","0.000000","0.000000"

> 'PS C:\Users\andib> typeperf '\GPU Engine(*_Cuda)\Utilization Percentage'

> '"(PDH-CSV 4.0)","\\ANDINI\GPU Engine(pid_6752_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_1596_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_11828_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_13568_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_18248_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_2616_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_16720_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_3272_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_16660_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage","\\ANDINI\GPU Engine(pid_4_luid_0x00000000_0x000154C7_phys_0_eng_8_engtype_Cuda)\Utilization Percentage"
"05/16/2020 08:49:54.093","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","93.848162","0.000000"
"05/16/2020 08:49:55.169","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","96.760047","0.000000"
"05/16/2020 08:49:56.221","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","95.196571","0.000000"
"05/16/2020 08:49:57.279","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","94.176305","0.000000"
"05/16/2020 08:49:58.367","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","94.657825","0.000000"
"05/16/2020 08:49:59.398","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","0.000000","95.981860","0.000000"

**Comment by XhmikosR** [comment]
Sorry, can't help with that. This repo is mainly a fork.

**Comment by andibuwono** [comment]
Oh, I see thanks
