### ISSUE TITLE
PerfmonBar doesn't work on non English systems

### ISSUE THREAD

**Issue by XhmikosR** [XhmikosR/perfmonbar#2]
@kasper93: if you have some time, I'd really like some help with this. I cannot figure out where it fails. I know for sure it's not `Configuration::GetConfigPath()` not `Configuration::Read()`.

TIA

EDIT:
Apparently `CPerfMon::GetValues()` fails.

``` cpp
PDH_STATUS pdhStatus = PdhCollectQueryData(_query);

if (pdhStatus != ERROR_SUCCESS) {
    return stdext::hash_map<std::wstring, double>();
}
```

EDIT 2:
OK, I think I made some more progress. It must be because `PdhAddCounter` takes into account the locale.

**Comment by XhmikosR** [comment]
@kasper93: if you have some time, I'd really like some help with this. I cannot figure out where it fails. I know for sure it's not `Configuration::GetConfigPath()` not `Configuration::Read()).

TIA

**Comment by XhmikosR** [comment]
Apparently `CPerfMon::GetValues()` fails.

```
    PDH_STATUS pdhStatus = PdhCollectQueryData(_query);

    if (pdhStatus != ERROR_SUCCESS) {
        return stdext::hash_map<std::wstring, double>();
    }
```

**Comment by XhmikosR** [comment]
OK, I think I made some more progress. It must be because `PdhAddCounter` takes into account the locale.

**Comment by radek-bruha** [comment]
I am using PerfmonBar with non English system language and it's working good. Only problem here is that you cannot use English names of counters - you need to use localized ones. So for example instead of `\Processor Information(*)\% Processor Time` I need to use `\Informace o procesoru(*)\% času procesoru` (Czech localization). English names not working even in PowerShell, so I think this cannot be solved. Only real problem what I see here is that default configuration not working for non English localization, so people may get bad decision that PerfmonBar not working at all.

**Comment by XhmikosR** [comment]
True that. Care to make a PR adding to docs  and/or website please?

**Comment by noeljf** [comment]
Some sample of the config file  from french system : 
once the right counter is found in exported counters file seems pretty good.

<?xml version="1.0" encoding="utf-8"?>

<perfbar>
    <counters>
        

        <counter name="cpupct" value="\Processeur(*)\% temps processeur"/>
        <counter name="processCount" value="\Système\Processus"/>
        <counter name="cpufreq" value="\Informations sur le processeur(*)\Fréquence du processeur"/>
        <counter name="cputhread" value="\Processus(*)\Nombre de threads"/>

        <counter name="mem" value="\Mémoire\Mégaoctets disponibles"/>
        <counter name="memval" value="\Mémoire\Octets validés"/>
        
        

        <counter name="netin" value="\Interface réseau(Intel[R] Centrino[R] Advanced-N 6205)\Octets reçus/s"/>
        <counter name="netout" value="\Interface réseau(Intel[R] Centrino[R] Advanced-N 6205)\Octets envoyés/s"/>

        <counter name="freediskC" value="\Disque logique(C:)\Mégaoctets libres"/>
        <counter name="freediskF" value="\Disque logique(D:)\Mégaoctets libres"/>

   </counters>
    <pages>
        
        <page offsetY="6">
            <lines>
                <line fontFamily="Calibri" fontSize="7" fontItalic="false" fontBold="true" fontColor="FFFFFF">
                    
                    
                    <display prefix="CPU " suffix=" thr@" counter="cputhread" decimals="0" characters="2"/>
                    <display prefix="" suffix="Ghz" counter="cpufreq" decimals="1" divide="1000" characters="3"/>
                    <display prefix=" (" suffix="%)" counter="cpupct" characters="3"/>
                    <display prefix=" | Processes: " suffix="" counter="processCount"/>
                </line>
                <line fontFamily="Calibri" fontSize="7" fontItalic="false" fontBold="true" fontColor="FFFFFF">
                    <display prefix="Ram: " suffix="GB" counter="mem" decimals="2" divide="1024"/>
                    <display prefix=" (" suffix="GB)" counter="memval" decimals="2" divide="1073741824"/>
                    
                    <display prefix=" | Net ˅" suffix="KB/s" counter="netin" decimals="1" divide="1024"/>
                    <display prefix=" ˄" suffix="KB/s" counter="netout" decimals="1" divide="1024"/>
                </line>
                <line fontFamily="Calibri" fontSize="7" fontItalic="false" fontBold="true" fontColor="FFFFFF">
                    <display prefix="Free C: " suffix=" GB" counter="freediskC" decimals="1" divide="1024"/>
                    <display prefix=" | D: " suffix=" GB" counter="freediskF" decimals="1" divide="1024"/>
                </line>
            </lines> 
        </page>
        <page offsetY="6">
            <lines>
                <line fontFamily="Segoe UI" fontSize="8" fontItalic="false" fontBold="true" fontColor="FFFFFF">
                    <display prefix="Free C: " suffix=" GB" counter="freediskC" decimals="1" divide="1024"/>
                </line>
            </lines>
        </page>
    </pages>
    <settings minSizeX="10" minSizeY="10">
    </settings>
</perfbar>
