### ISSUE TITLE
Network speed seems wrong

### ISSUE THREAD

**Issue by Andy-ZA** [XhmikosR/perfmonbar#26]
I compared the readings for MB/s against windows Task Manager. They seemed out by 8:
Default in congif.xml: display prefix=" · D: " suffix=" MB/s" counter="netin" decimals="1" divide="1048576"
I had change to this: display prefix=" || U: " suffix=" MB/s" counter="netout" decimals="1" divide="131072"
This is 1024*1024/8.

Now my MB/s matches Task Manager.

Thanks for the program.

**Comment by XhmikosR** [comment]
Feel free to submit a PR to change the defaults, but while at it update the KB/s too :)

**Comment by XhmikosR** [comment]
Closing since the counter can be customized. If you want Mbps you could adapt the counter.
