### ISSUE TITLE
Support for "add" and "subtract" operations

### ISSUE THREAD

**Issue by Plexind** [XhmikosR/perfmonbar#27]
I'm trying to read CPU temp, but the counter comes back in Kelvin - whereas I want Celcius. All I need to to is subtract 273.15 from the counter value. Really you would only need to implement an "add" then I can just put in a negative number.

**Comment by noeljf** [comment]
> 
> 
> I'm trying to read CPU temp, but the counter comes back in Kelvin - whereas I want Celcius. All I need to to is subtract 273.15 from the counter value. Really you would only need to implement an "add" then I can just put in a negative number.

**Comment by noeljf** [comment]
👍

**Comment by radek-bruha** [comment]
@Plexind I implemented it for you. :) Unfortunately my notebook does not support it, so I will not enjoy CPU temperature with you. :(

**Comment by noeljf** [comment]
will test it , thx a lot give you feedback soon

**Comment by noeljf** [comment]
can you provide me a compiled version ? I'm unable to do something with your modif

**Comment by tapufd** [comment]
Hi,
Is the subtract (and/or add) functionality implemented in the latest release (1.0.5.171)?
It doesn't seem to work for me if I add subtract="" to the display element... nothing is subtracted for any value.
Maybe it would be good to add some general math="" in which you can add/subtract/divide/multiply/... as much as you want?!
For example: math="(*20/100)-10" -> perf counter is multiplied by 20 and divided by 100 and then 10 is subtracted.
Maybe harder to implement, but would make your tool more complete.
To make it even more better, maybe add the possibility to use in the math other perf counters... :-)
/T

**Comment by ma-zal** [comment]
#44

**Comment by XhmikosR** [comment]
`add` was added in #44 and included in https://github.com/XhmikosR/perfmonbar/releases/tag/1.0.7.185
