### ISSUE TITLE
Counter contening  '   doesn't work 

### ISSUE THREAD

**Issue by noeljf** [XhmikosR/perfmonbar#28]
On a french system counter contening  '   doesn't work is there a substitution possible like [ ] for ( ) ? Thanks

**Comment by Ikalou** [comment]
You have to be careful to use the right kind of quote character in the name.

For me copy/pasting straight from the output of "typeperf -q" in PowerShell worked.

**Comment by P4NAD3ROXIS** [comment]
How??

**Comment by XhmikosR** [comment]
See also #2
