### ISSUE TITLE
Value is centered automatically

### ISSUE THREAD

**Issue by uladz-zubrycki** [XhmikosR/perfmonbar#37]
Is it possible float value to the left or to the right instead of centering it? I tried to play with `characters` attribute, but it's no help for the case. 

Let me show you what I mean. I have CPU and RAM counters and want those to have the same width, so that my other counters go nicely aligned. 

Everything is cool if both CPU and RAM have two digits in the value. 
![image](https://user-images.githubusercontent.com/5411526/108211656-ff979500-713d-11eb-9bb3-7c8f39c5d786.png)

But it looks bad, when CPU consumption is not that high.
![image](https://user-images.githubusercontent.com/5411526/108211694-10480b00-713e-11eb-9814-b60f37a1b5ae.png)

Notice how arrows for download and upload speeds change their position. Moreover they jump all the time as values change and it disturbs.

Temporarily fixed by moving counters around, but it's not ideal. 
![image](https://user-images.githubusercontent.com/5411526/108213164-c7915180-713f-11eb-94da-6ba5223b9b69.png)

Thanks for the app!

**Comment by XhmikosR** [comment]
Yeah, it's a font matter.
