### ISSUE TITLE
Support for GPU usage indicator

### ISSUE THREAD

**Issue by sylvainlapeyrade** [XhmikosR/perfmonbar#38]
Hello,
First, thank you very much for the app.

I would like to know if it is possible to monitor the GPU usage. I am trying to do so using the counter: "\GPU Engine(*)\Utilization Percentage" but I am almost always getting 0.0%. When I test the counter in the shell, I see there are multiple values and the first one is almost always 0. So I assume we have to display the sum of all the values:
`typeperf "\GPU Engine(*)\Utilization Percentage`
![image](https://user-images.githubusercontent.com/38108837/114421932-1a264180-9bb6-11eb-8da5-d0f36329aff4.png)

Is it possible to display the sum of these values?

Thanks again.

**Comment by XhmikosR** [comment]
Hello.

From a quick look, I don't think it's just the sum. But PRs are always welcome. :)

**Comment by TyraVex** [comment]
If someone is reading this there is the possibility to use "\GPU Engine(*engtype_3D)\Utilization Percentage"
