### ISSUE TITLE
Not completely visible 

### ISSUE THREAD

**Issue by adas0496** [XhmikosR/perfmonbar#42]
The text is not visible completely. I am seeing only first 2 to 3 characters. See screenshot below.
![image](https://user-images.githubusercontent.com/13404532/128623124-b6f7d8ed-7cf5-4613-b5e0-76d43a07e273.png)

I am using Windows 10 Pro 20H2 19042.1110 .

It might be a problem with total width or horizontal offset of the toolbar. 
Any ideas how to fix it?

**Comment by XhmikosR** [comment]
Unlock taskbar and resize as needed.

**Comment by adas0496** [comment]
Thanks for the help. 🙂
