### ISSUE TITLE
How to get counter name?

### ISSUE THREAD

**Issue by chaoscreater** [XhmikosR/perfmonbar#48]
I ran this:
typeperf -q > counters.txt

And it doesn't tell me the counter name, which is used by the config....

![image](https://user-images.githubusercontent.com/18227319/145516517-fd98ecd7-2126-4d43-8b93-8b07ffc4ef26.png)

**Comment by XhmikosR** [comment]
Those are the counter names. Not sure what your question is exactly... You can add any valid counter in the config.

**Comment by chaoscreater** [comment]
UHH, no that's not right. Those are the counter values. I mean, this is defined in the config....

![image](https://user-images.githubusercontent.com/18227319/145524728-7e015fd4-2244-43f8-804b-27b93207ef70.png)

If I change the counter name for e.g. "cpu" or "mem" to something else completely different, then it shows as N/A in the taskbar. Just using the counter value is not enough, I need to give it the proper counter name as well.

**Comment by XhmikosR** [comment]
The `name` is whatever you want it to be. You need to make sure you are using the same name in the counter afterwards, and reload config.

That's all that's it to it.

**Comment by chaoscreater** [comment]
Thanks, got it working,

One more question, how come when I'm using the hex code for RED (FF0000), I get blue instead?

**Comment by XhmikosR** [comment]
No idea, could be due to taskbar's transparency or something. I don't have a solution to that (and I have noticed it on some cases myself).

**Comment by chaoscreater** [comment]
I'm not using any transparency though but thanks anyway.

**Comment by chaoscreater** [comment]
Hmm I think there's a bug in the code....

Hex code for blue gives red.
Hex code for red gives blue.

0000FF is blue and FF4500 is red. They give opposite colours.

**Comment by XhmikosR** [comment]
You are welcome to submit a PR, could be a bug.
