### ISSUE TITLE
Not working with Intel Network Interface

### ISSUE THREAD

**Issue by AZZmatic** [XhmikosR/perfmonbar#5]
My NIC according to Windows 7 is this:
Intel(R) 82566DM-2 Gigabit Network Connection
That is not the ® symbol but two parenthesis around an R.  Not sure if the () is causing the issue.

**Comment by anonimuos** [comment]
Not working for me either. My NIC name is:
Killer(R) Wireless-AC 1550i Wireless Network Adapter (9560NGW) 160MHz

Copy-pasted from the output.txt generated by typeperf -qx > output.txt. I pasted it between the ( ) but refreshing it does not work.
