### ISSUE TITLE
How to handle special character

### ISSUE THREAD

**Issue by noeljf-kyndryl** [XhmikosR/perfmonbar#50]
Hello, 

my network card is named : Intel(R) Wi-Fi 6 AX201 160MHz   with 2 parenthesis after Intel.  (copy/paste from registry.)

when I use the counter : \Network Interface(*)\Bytes Total/sec

and try to relace the * with the network card, This i not working probably do to misunderstanding of parenthesis by the perfmonbar or a tips I do not know.

Thanks for answering and/or help to me;

**Comment by XhmikosR** [comment]
https://github.com/XhmikosR/perfmonbar/blob/b96d3ab6d5f4864394173d827ce9881fe80671eb/src/config.xml#L8
