### ISSUE TITLE
I have VS2019, and I cannot build both perfmonbar-1.0.4.152.zip and perfmonbar-1.0.5.171.zip

### ISSUE THREAD

**Issue by exec228** [XhmikosR/perfmonbar#55]
Greetings!

I have VS2019, and I cannot build both perfmonbar-1.0.4.152.zip and perfmonbar-1.0.5.171.zip
Result is:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	RC1015	cannot open include file 'Version.h'.	PerfmonBar	C:\PerfMonBar\source\src\PerfmonBar.rc	10	

```
What am I doing wrong?
By the way, next line #include "winresrc.h" is not realistic too: no such file delivered.

(That's what I am doing because Windows Defender insistently destroys .exe of release, and it cannot be switched off by domain rules)

Thank you!

**Comment by XhmikosR** [comment]
You need VS2022 and you need to clone the repo.

**Comment by exec228** [comment]
I gitted out 1.0.5.171 and the contents is the same, as in zip: "no vershion.h".

(Why would I need 2022 when having 2019 as a corporate tech-stack, and project was configured to 2019 in recent version?)
