### ISSUE TITLE
Is it possible after silent install to auto run perfmonbar

### ISSUE THREAD

**Issue by ndinev** [XhmikosR/perfmonbar#57]
I was able to install and configure perfmonbar bar and configure it for my needs. Next steps is to silently install configure and enable it without user interaction.
here are the steps I foresee:
1. do install with option /silent
2. replace config.xml with my config
3. enable perfmonbar to be visible(if needed reload config also)

1 and 2 are easy. I need some help how to do 3 in automatic way - is this possible?

**Comment by XhmikosR** [comment]
I don't think that's possible, but do let us know if you find a way.
