### ISSUE TITLE
document how to uninstall, and/or provide an uninstall script

### ISSUE THREAD

**Issue by HarlanH** [XhmikosR/perfmonbar#58]
Hi, thanks for building and maintaining perfmonbar! It doesn't quite support my needs, so I'd like to uninstall it. I can't find an option how to do so. May I suggest adding something to the README, if it's easy to do as an end-user, or adding an option in the toolbar itself,  if not, to help people uninstall? Thank you!

**Comment by XhmikosR** [comment]
Uninstall is done the standard way... Either from the control panel or from the start menu folder shortcut.
