### ISSUE TITLE
如果我想调用物理内存占比，请问该如何调用？

### ISSUE THREAD

**Issue by my52029** [XhmikosR/perfmonbar#59]
软件确实做到了简单实用，我简单自定义了样式，和任务栏风格也比较搭配，我希望还能调用物理内存的占比，但是不知道<counter name="mem" value="\**\**"/>这里关于内存计数是如何写的?还有是否支持？

**Comment by XhmikosR** [comment]
Sorry, I don't speak your language, please use English.

**Comment by my52029** [comment]
I just used it yesterday, and the software has really made it simple and practical. I have simply customized the style, which also matches the taskbar style. I hope to be able to call the proportion of physical memory, but I don't know how to write the memory count here<counter name=/> Is there any support? If it is not supported, do you need to add it to the counter before calling it?

**Comment by XhmikosR** [comment]
Please see https://github.com/XhmikosR/perfmonbar#how-to-find-the-desired-settings

**Comment by my52029** [comment]
I have already set up the system's default counters.txt according to the operating instructions, and have written all the information in it. I have seen that information such as CPU usage, memory usage, disk space, and network traffic has been detected, but there is no physical memory usage ratio I want. After checking the relevant information, it seems that the system does not have this item by default.

**Comment by XhmikosR** [comment]
If your system doesn't have the counter you want, there's nothing more that can be done, sorry :/

**Comment by my52029** [comment]
I see. Thank you for your patient response. I hope the software gets better and better.

**Comment by nicolas2k** [comment]
> Please see https://github.com/XhmikosR/perfmonbar#how-to-find-the-desired-settings

is it compliant for Windows 11 ?

**Comment by XhmikosR** [comment]
That's unrelated to this issue, and no, see #46
