### ISSUE TITLE
Problem with deskband size

### ISSUE THREAD

**Issue by Volkanite** [XhmikosR/perfmonbar#6]
I have a problem where the deskband in really small, defaults to the size of PerfBar.cpp/line 62/DESKBANDINFO::ptMinSize.x which is 10. I had to change this value to 60 and recompile to get anything useful. Should it not update the size by itself? Can I set the minimum size through config file? I'm on win 7 x64.

Before:
![toosmall](https://cloud.githubusercontent.com/assets/9159000/8423173/3c5f77ac-1eb3-11e5-85a3-e88c76404ae2.jpg)
After(60 just to test):
![after](https://cloud.githubusercontent.com/assets/9159000/8423185/777d9dd2-1eb3-11e5-94a4-0c5cc9028edb.jpg)

**Comment by XhmikosR** [comment]
I'm not sure I follow. In the second screenshot you simply could right click, choose not to lock the taskbar and resize it.

**Comment by Volkanite** [comment]
Did not know i could do that! Thanks and great tool!
