### ISSUE TITLE
How do I modify config.xml to see physical memory?

### ISSUE THREAD

**Issue by JB330** [XhmikosR/perfmonbar#7]
Perfmon shows a pagefile usage, but I want to see a physical momory usage.
Thank you.

**Comment by XhmikosR** [comment]
You can only use whatever counters Windows provides us with. I don't think they provide such a counter.

**Comment by XhmikosR** [comment]
Either way, https://github.com/XhmikosR/perfmonbar/blob/master/src/config.xml#L5

**Comment by JB330** [comment]
OK, Thank you! And thank you again your effort to provide an awesome application!
