### ISSUE TITLE
Continue to update with taskbar hidden?

### ISSUE THREAD

**Issue by s-rog** [XhmikosR/perfmonbar#9]
Currently when the task bar auto hides perfmonbar seems to stop running and display jumbled text, updating only after a short delay after showing the task bar again. Is it possible to change this behavior?

**Comment by XhmikosR** [comment]
What's the point of updating if the toolbar is hidden?

Either way, I have no idea.

**Comment by s-rog** [comment]
it's just to stop the display of garbled text when you unhide the taskbar and instead display the correct metrics

**Comment by XhmikosR** [comment]
I have no idea about this, sorry.

**Comment by s-rog** [comment]
no problem, thanks anyway!
